### ISSUE TITLE
Linux Circle-CI failing

### ISSUE THREAD

**Issue by wfspotz** [conda-forge/pytrilinos-feedstock#1]
The Linux Circle-CI is flagged as failing. Checking the report, everything appears to build and test properly, but the report ends with

    TEST END: /feedstock_root/build_artefacts/linux-64/pytrilinos-12.10.1-py27_0.tar.bz2
    INFO:conda_build.config:--dirty flag and --keep-old-work not specified.Removing build/test folder after successful build/test.

    # Automatic uploading is disabled
    # If you want to upload package(s) to anaconda.org later, type:

    anaconda upload /feedstock_root/build_artefacts/linux-64/pytrilinos-12.10.1-py27_0.tar.bz2

    # To have conda build upload to anaconda.org automatically, use
    # $ conda config --set anaconda_upload yes

    anaconda_upload is not set.  Not uploading wheels: []
    + test -f /home/circleci/test/build_artefacts/conda-forge-build-done
    + exit 1
    Exited with code 1

I don't know where to proceed from here.

**Comment by isuruf** [comment]
I don't see anything wrong with the build. Can you restart the build?

**Comment by wfspotz** [comment]
Here are the results:
    https://circleci.com/api/v1.1/project/github/conda-forge/pytrilinos-feedstock/2/output/105/0?file=true

**Comment by isuruf** [comment]
@conda-forge/core, have you seen this issue before?

**Comment by jakirkham** [comment]
Looks like the upload failed, but am not sure why. Could be some networking issue that is not being reported. Went ahead and just restarted to see what happens. If it still fails, we should look more closely.

**Comment by wfspotz** [comment]
@jakirkham Any ideas?

**Comment by isuruf** [comment]
@jakirkham, @ocefpaf, ping

**Comment by jakirkham** [comment]
[Certain kinds of tests fouled up deployment]( https://github.com/conda-forge/libarchive-feedstock/issues/3#issuecomment-227556577 ) before. Could try disabling the tests on Linux only and see if that helps. Only a guess though. Unfortunately can't give it much more thought near term.

**Comment by wfspotz** [comment]
So the error is

    + test -f /home/circleci/test/build_artefacts/conda-forge-build-done
    + exit 1
    Exited with code 1

which looks like a file is missing. Where does that file come from?

**Comment by zonca** [comment]
It looks like it is still failing for the same reason:

```
WARNING: conda-build appears to be out of date. You have version 2.1.18 but the
latest version is 3.4.0. Run

conda update -n root conda-build

to get the latest version.

+ source /opt/conda/bin/activate /feedstock_root/build_artefacts/pytrilinos_1517518006733/_t_env
+ /feedstock_root/build_artefacts/pytrilinos_1517518006733/_t_env/bin/python -s /feedstock_root/build_artefacts/pytrilinos_1517518006733/test_tmp/run_test.py
import: 'PyTrilinos.Teuchos'
import: 'PyTrilinos.Epetra'
import: 'PyTrilinos.TriUtils'
import: 'PyTrilinos.Tpetra'
import: 'PyTrilinos.EpetraExt'
import: 'PyTrilinos.Domi'
import: 'PyTrilinos.AztecOO'
import: 'PyTrilinos.Galeri'
import: 'PyTrilinos.Amesos'
import: 'PyTrilinos.IFPACK'
import: 'PyTrilinos.Komplex'
import: 'PyTrilinos.ML'
import: 'PyTrilinos.Anasazi'
TEST END: /feedstock_root/build_artefacts/linux-64/pytrilinos-12.10.1-py27_1.tar.bz2
INFO:conda_build.config:--dirty flag and --keep-old-work not specified.Removing build/test folder after successful build/test.

# Automatic uploading is disabled
# If you want to upload package(s) to anaconda.org later, type:

anaconda upload /feedstock_root/build_artefacts/linux-64/pytrilinos-12.10.1-py27_1.tar.bz2

# To have conda build upload to anaconda.org automatically, use
# $ conda config --set anaconda_upload yes

anaconda_upload is not set.  Not uploading wheels: []
```

It looks like all tests pass, the conda package is ready, but it fails to upload.
Is it possible the BINSTAR_TOKEN is not correct?

**Comment by zonca** [comment]
Also I wonder why it is using such a old version of `conda-build`, but not sure where that is set...

**Comment by wfspotz** [comment]
As of 5 months ago, the Linux Circle-CI tests are passing, so I am marking this as closed.
