### ISSUE TITLE
Can't import modules on Mac OS X

### ISSUE THREAD

**Issue by guyer** [conda-forge/pytrilinos-feedstock#10]
```
$ conda create -n trilinos --channel conda-forge "mpich=3.2.*" mpi4py python "numpy>=1.7" pytrilinos
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment /Users/guyer/anaconda/envs/trilinos:

The following NEW packages will be INSTALLED:

    blas:            1.1-openblas                  conda-forge
    ca-certificates: 2018.1.18-0                   conda-forge
    certifi:         2018.1.18-py27_0              conda-forge
    libgfortran:     3.0.0-0                       conda-forge
    mpi4py:          3.0.0-py27_0                  conda-forge
    mpich:           3.2-5                         conda-forge
    ncurses:         5.9-10                        conda-forge
    numpy:           1.14.1-py27_blas_openblas_200 conda-forge [blas_openblas]
    openblas:        0.2.20-7                      conda-forge
    openmpi:         3.0.0-0                       conda-forge
    openssl:         1.0.2n-0                      conda-forge
    pip:             9.0.1-py27_1                  conda-forge
    python:          2.7.14-4                      conda-forge
    pytrilinos:      12.10.1-py27_1                conda-forge
    readline:        7.0-0                         conda-forge
    scipy:           1.0.0-py27_blas_openblas_201  conda-forge [blas_openblas]
    setuptools:      38.5.1-py27_0                 conda-forge
    sqlite:          3.20.1-2                      conda-forge
    tk:              8.6.7-0                       conda-forge
    wheel:           0.30.0-py27_2                 conda-forge
    zlib:            1.2.11-0                      conda-forge

Proceed ([y]/n)? 

certifi-2018.1 100% |###########################################################################################################| Time: 0:00:00   3.81 MB/s
setuptools-38. 100% |###########################################################################################################| Time: 0:00:00   3.40 MB/s
#
# To activate this environment, use:
# > source activate trilinos
#
# To deactivate an active environment, use:
# > source deactivate
#

$ source activate trilinos
(trilinos) $ python exAztecOO.py 
Traceback (most recent call last):
  File "exAztecOO.py", line 71, in <module>
    from PyTrilinos import Epetra
  File "/Users/guyer/anaconda/envs/trilinos/lib/python2.7/site-packages/PyTrilinos/Epetra.py", line 73, in <module>
    _Epetra = swig_import_helper()
  File "/Users/guyer/anaconda/envs/trilinos/lib/python2.7/site-packages/PyTrilinos/Epetra.py", line 72, in swig_import_helper
    return importlib.import_module('_Epetra')
  File "/Users/guyer/anaconda/envs/trilinos/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named _Epetra
```

**Comment by raviapatel** [comment]
Same issue also appears on ubuntu any solution yet?

**Comment by wfspotz** [comment]
It works for me on Mac OS X and on a Red Hat system I have access to. @guyer and @raviapatel, what happens when you run

    python -c "import PyTrilinos, os; print os.listdir(os.path.dirname(PyTrilinos.__file__))"

**Comment by wfspotz** [comment]
Great!

**Comment by Govinda7** [comment]
Hi @wfspotz,
 
I am having a similar issue.

I have installed pytrilinos with the following procedure:
1) conda config --add channels conda-forge
Once the conda-forge channel has been enabled, pytrilinos can be installed with:
2) conda install pytrilinos
3) conda search pytrilinos --channel conda-forge

I am getting the following error:
Python 2.7.16 |Anaconda, Inc.| (default, Mar 14 2019, 21:00:58) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from PyTrilinos import Epetra, EpetraExt, IFPACK, AztecOO
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/govinda/anaconda3/lib/python2.7/site-packages/PyTrilinos/Epetra.py", line 73, in <module>
    _Epetra = swig_import_helper()
  File "/home/govinda/anaconda3/lib/python2.7/site-packages/PyTrilinos/Epetra.py", line 72, in swig_import_helper
    return importlib.import_module('_Epetra')
  File "/home/govinda/anaconda3/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named _Epetra


And this is the output of :
python -c "import PyTrilinos, os; print os.listdir(os.path.dirname(PyTrilinos.__file__))"
['_IFPACK.so', 'Anasazi.py', 'AztecOO.pyc', 'typed_dict.pyc', 'EpetraExt.py', '_Tpetra.so', 'typed_dict.py', 'Amesos.pyc', 'Domi.py', 'Epetra.pyc', 'TriUtils.py', '_ML.so', '_Teuchos.so', 'Anasazi.pyc', 'TriUtils.pyc', 'Galeri.pyc', '_Anasazi.so', 'typed_tuple.py', 'typed_tuple.pyc', '__init__.py', 'Teuchos.py', 'Galeri.py', '_Domi.so', '_AztecOO.so', 'IFPACK.pyc', 'Teuchos.pyc', '_EpetraExt.so', 'Komplex.py', '_Komplex.so', 'EpetraExt.pyc', 'ML.pyc', 'PropertyBase.py', '_TriUtils.so', '_Galeri.so', 'Amesos.py', 'IFPACK.py', 'ML.py', 'typed_list.py', 'typed_list.pyc', '__init__.pyc', 'Epetra.py', 'Tpetra.py', 'Tpetra.pyc', 'PropertyBase.pyc', 'Komplex.pyc', 'Domi.pyc', '_Epetra.so', '_Amesos.so', 'AztecOO.py']
