### ISSUE TITLE
Can't import modules on macOS (again)

### ISSUE THREAD

**Issue by guyer** [conda-forge/pytrilinos-feedstock#21]
As previously reported (#10), imports on macOS [fail](https://travis-ci.org/usnistgov/fipy/jobs/631372702) with
```
ImportError: Unable to load solver trilinos: No module named _ML
```
or similar. 

This was previously remedied by the upload of 12.10.1 build 2. 

Can you please remove or hide the [`osx-64/pytrilinos-12.10.1-py27_0.tar.bz2`](https://anaconda.org/conda-forge/pytrilinos/12.10.1/download/osx-64/pytrilinos-12.10.1-py27_0.tar.bz2) and [`osx-64/pytrilinos-12.10.1-py27_1.tar.bz2`](https://anaconda.org/conda-forge/pytrilinos/12.10.1/download/osx-64/pytrilinos-12.10.1-py27_1.tar.bz2) builds? They are broken and conda seems to keep changing its precedence semantics, such that build 2 is not reliably found first.

**Comment by isuruf** [comment]
Done
