### ISSUE TITLE
Post-processing script

### ISSUE THREAD

**Issue by wfspotz** [conda-forge/pytrilinos-feedstock#3]
I would like to add a post-processing script that runs after PyTrilinos gets built that alters the export files for cmake and make. it will remove the `pytrilinos` library from these files so that users trying to link against Trilinos will not link against any of the Python wrappers.

I think I know how to do this, so this issue report is just tracking purposes.

**Comment by isuruf** [comment]
Have you also thought about splitting trilinos and pytrilinos? For eg: You have a trilinos-feedstock and pytrilinos-feedstock and pytrilinos depends on trilinos. (I know they have one build system, but if you do the same build in trilinos and pytrilinos, conda will package only the newer files, i.e. the files related to the python wrappers in the pytrilinos case.)

**Comment by wfspotz** [comment]
I am open to splitting. I will open a separate issue for it.

However, I believe the pytrilinos installer will package the export files, which will still need to be fixed.

**Comment by isuruf** [comment]
> However, I believe the pytrilinos installer will package the export files, which will still need to be fixed.

If Trilinos is built without python, will it have export files? If it does, the pytrilinos installer will only change that file right? If so, there's no need to fix.

**Comment by wfspotz** [comment]
The export files, if you use them in your project, tell your build system to link with `libpytrilinos` which is a bug. Until the Trilinos framework folks fix this, I'll need to post-process the export files prior to their installation.

**Comment by wfspotz** [comment]
The post-processing script is `Trilinos/packages/PyTrilinos/util/configFix.py.in` and it gets called from `pytrilinos-feedstock/recipe/build.sh`, so this issue is fixed.
